name: Pipeline
on:
  push:

jobs:
  test-orders:
    runs-on: [ viarise ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
        with:
          module: some-module
